#!/usr/bin/python

"""
#----------------------------------------------------------------
Author: Jason Gors <jasonDOTgorsATgmail>
Creation Date: 10-22-2013
Purpose: to update packages installed w/ pip.
#----------------------------------------------------------------
"""

import pip
import site
import argparse
from subprocess import call


parser = argparse.ArgumentParser(description="Use to update pip packages.")
parser.add_argument('--version', action='version', version='%(prog)s 1.0')

group = parser.add_mutually_exclusive_group()
group.add_argument("-e", "--everything", action="store_true", help="update all packages.")
group.add_argument("-l", "--local", action="store_true", help="update only packages installed locally (in userbase).")

args = parser.parse_args()


update_all_pkgs = args.everything
update_only_local_pkgs = args.local
if not (update_all_pkgs or update_only_local_pkgs):
    print("Error: need to specify an argument, see: pip_updater -h") 

local_install_area = site.getuserbase()


def updater(pkg_name):
    print("\n{0}\n\t\tUpdating {1}\n{0}".format('-'*50, pkg_name))
    call(["pip", "install", "--user", "--upgrade", pkg_name])


def main():
    pkgs = pip.get_installed_distributions()
    for pkg in pkgs:
        pkg_name = pkg.project_name
        if update_all_pkgs:
            updater(pkg_name)
        elif update_only_local_pkgs:
            if local_install_area in pkg.location:
                updater(pkg_name)

if __name__ == '__main__':
    main()
